language: php

php:
  - 7.1
  - 7.2
#  - nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  email: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - cp config/env.example.php config/env.php
  # Same as in integration.php
  - mysql -e 'create database slim_test;'
  - cd $TRAVIS_BUILD_DIR


script:
  - ant phpunit-coverage
  - ant phpstan
  - ant check-docblocks

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

notifications:
email: false